new helm chart for the operator
stakater/IngressMonitorController pull request #297
Opened 2020-12-02 10:03 UTC by magneticz

As I said in my comment in the issue, I am not a helm expert, so it might not be the best chart you see, but I can update the chart with your comments, if there are any.

I just copied over old chart and made it work with new resource objects. Basically it's a derived from old helm chart and yaml files from /deploy folder in this repo. 

Closes #268

2020-12-02 10:08 UTC, stakater-user commented
@magneticz Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins-delivery.stakater.com/job/Stakater/job/IngressMonitorController/job/PR-297/1/) has Failed!

2020-12-04 09:10 UTC, stakater-user commented
@magneticz Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins-delivery.stakater.com/job/Stakater/job/IngressMonitorController/job/PR-297/2/) has Failed!

2020-12-08 15:29 UTC, magneticz commented
Hi all, 
Any pointers on how to fix the failing build? I didn't touch any coding part, so not sure why it is failing at all. 
If there are any comments regarding the chart itself, would be happy to fix those as well.

2021-01-07 14:59 UTC, rasheedamir commented
@josedev-union can you plz take a look?

2021-01-21 19:38 UTC, twardnw commented
I'd also be willing to look at helping fix whatever is wrong, but without knowing what has failed, hard to do anything :( @josedev-union , what's the word?

2021-01-21 20:39 UTC, stakater-user commented
@josedev-union Image is available for testing. `docker pull stakater/IngressMonitorController:SNAPSHOT-PR-297-32ed17aa`

2021-01-27 14:59 UTC, cuttingedge1109 commented
Sorry for late response.
let me check shortly

2021-01-28 09:36 UTC, cuttingedge1109 commented on deploy/chart/ingressmonitorcontroller/Chart.yaml
> +appVersion: 1.0.47
Set the appVersion as the latest release version `2.0.10`

2021-01-28 09:39 UTC, cuttingedge1109 requested changes

2021-01-28 09:39 UTC, cuttingedge1109 commented on deploy/chart/ingressmonitorcontroller/README.md
> +| image.tag          | Version of ingressMonitorController Image                                                      | `1.0.47`                        | `1.0.47`
Please sync the default value with the values.yaml file.
`2.0.2` in values.yaml file now

2021-01-28 09:39 UTC, cuttingedge1109 commented on deploy/chart/ingressmonitorcontroller/README.md
> +| providers.apiKey        | ApiKey of the provider                                                    | `u956-afus321g565fghr519`            | `your-api-key`                       |
Seems better to remove the default value for `providers.apiKey` in values.yaml file and set "" here.

2021-01-28 09:39 UTC, cuttingedge1109 commented on deploy/chart/ingressmonitorcontroller/values.yaml
> +    apiKey: 0008465a8fdc6b5bb96ac30e7b6fdd278d20d346
I recommend to set empty string here

2021-02-04 23:46 UTC, twardnw commented
@magneticz , if you would like, I addressed the feedback in this commit : https://github.com/amazeeio/IngressMonitorController/commit/1cd85492798e003933f554d7242d1eabe69de662

2021-02-17 08:34 UTC, magneticz commented
hey all, sorry for the delay, I was on vacation and was not working. 

@twardnw do you want to merge your changes in this PR?

2021-02-18 00:14 UTC, twardnw commented
You should be able to add that repo as another remote and just merge the changes in

2021-02-26 10:24 UTC, Slutzky commented
Hi, is this MR going to merged in near future ? thank you in advance

2021-02-26 10:31 UTC, magneticz commented
hi all, sorry it took me so long to update the PR. I merged changes from @twardnw (thanks for addressing the comments).

2021-02-26 10:35 UTC, stakater-user commented
@magneticz Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/793f50d4cf6c61c9a7c91e0e922041eb0a201305/checks) has Failed!

2021-03-04 14:11 UTC, Slutzky commented
sorry to be annoying but is this MR will be closed ?

2021-03-14 08:39 UTC, rasheedamir commented
@magneticz can you plz make the PR green? and then lets get it merged

2021-03-30 09:30 UTC, cwrau commented
I'm also interested in this PR, can I help somehow?

2021-04-21 06:14 UTC, lgallard commented
@magneticz @stakater-user any update with this PR implementation? I would be great having the chart back!

2021-05-03 11:21 UTC, ahmedwaleedmalik commented
@kahootali is working on this in #315. It will released in a day or two. Apologies for the delay but I wasn't tracking this PR :)

2021-05-03 16:38 UTC, ahmedwaleedmalik commented
`v2.0.15` is out now, helm chart is back. ✌️

2021-05-03 16:38 UTC, ahmedwaleedmalik commented
Closing this PR now.

2021-05-03 16:38 UTC, closed without merging