[dev:stage] Adding kube-rbac-proxy resources for imc
stakater/IngressMonitorController pull request #388
Opened 2022-05-19 10:32 UTC by Muneebstakater

2022-05-19 10:34 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/0274ed1fb6ec3656d7a18ee81db85cf98e482d79/checks) has Failed!

2022-05-19 11:37 UTC, usamaahmadkhan requested changes

2022-05-19 11:37 UTC, usamaahmadkhan commented on charts/ingressmonitorcontroller/templates/deployment.yaml
> +        {{- if .Values.resources }}
Plz add resources for kube-rbac-proxy container

2022-05-19 11:43 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/a533a5ce90e91c2e91182f59466a9645f471a101/checks) has Failed!

2022-05-19 11:52 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/8e858086780332b4794d56eaff3cd25ee086863e/checks) has Failed!

2022-05-19 12:11 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/7627728dad8f7de6be7bd9f8782beb0e2e1b20be/checks) has Failed!

2022-05-19 19:20 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/ce999e9319f6787c33e985bfc47ebea7408c93a1/checks) has Failed!

2022-05-19 20:04 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/81f05975d8995b7630a14f89638dd4e9fe57f0f3/checks) has Failed!

2022-05-19 20:09 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/63156ba66d50bf0d458935e091215eb527d848be/checks) has Failed!

2022-05-20 10:49 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/ddf5f3983040c61b4cc1a1098582850510904274/checks) has Failed!

2022-05-20 11:02 UTC, usamaahmadkhan submitted a review, later dismissed

2022-05-20 11:02 UTC, usamaahmadkhan commented on charts/ingressmonitorcontroller/templates/deployment.yaml
> +          {{- toYaml .Values.resources | nindent 10 }}
what if the rbac proxy resources are different from the manage container? plz refer to the Forecastle chart

2022-05-20 20:50 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/011cef0f29b4683f6570d7f96d7064f3bbc261f9/checks) has Failed!

2022-05-24 07:37 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/c896071ee332b1f34372ae4e32988073a99780aa/checks) has Failed!

2022-05-24 07:42 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/bda25cf1d769dfa7c6e848fa24701b49496f5e14/checks) has Failed!

2022-05-24 07:51 UTC, stakater-user commented
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/ef9dee8b022b124c1351b39f24551c04885f6b2f/checks) has Failed!

2022-05-31 07:34 UTC, stakater-user commented
@stakater-user Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/IngressMonitorController/commit/ef9dee8b022b124c1351b39f24551c04885f6b2f/checks) has Failed!

2023-04-12 09:18 UTC, MuneebAijaz approved these changes

2023-04-12 09:18 UTC, merged